### ISSUE TITLE
Cannot add additional tags/columns

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sverhagen/mp3-browser#54] opened 2015-05-10 08:47 UTC
```
After reading about how to add custom columns at 
https://code.google.com/p/mp3-browser/wiki/CustomColumns I have resorted to 
asking the question outright...

How do I add ID3tags into the page that displays the audio files?! By default 
it only shows the title and author.


I have multiple tags that are associated with my Mp3 all need to be displayed. 
How do I do this?


```

Original issue reported on code.google.com by `ptrista...@gmail.com` on 12 Feb 2015 at 4:23

**Comment by sverhagen** [comment] 2015-09-02 07:10
Duplicate of issue #55.

**Closed by sverhagen** 2015-09-02 07:10 UTC
Labels: auto-migrated, duplicate, Priority-Medium, Type-Defect
